spring.application.name=api-biblioteca
# Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bibliotecadb
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD}

# Hibernate: Criar e atualizar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect