spring.application.name=api-biblioteca
# Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bibliotecadb
spring.datasource.username=postgres
spring.datasource.password=1234

# Hibernate: Cria e atualiza as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect